### ISSUE TITLE
find a stable version of node/npm and stick to it ...

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/asyncvoter-slack-command#51]
on 7.4 Paolo, Sam and Brent are all getting a weird error:

```
 Run a voting session
ReferenceError: logger is not defined
    at app.post (/Users/tansaku/Documents/GitHub/AgileVentures/asyncvoter-slack-command/async-voter.js:2:1147)
    at Layer.handle [as handle_request] (/Users/tansaku/Documents/GitHub/AgileVentures/asyncvoter-slack-command/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/tansaku/Documents/GitHub/AgileVentures/asyncvoter-slack-command/node_modules/express/lib/r
```

**Comment by tansaku** [comment]
this is now fixed, but note that README says using node 7.6 while we have 7.4 in the package.json
